### ISSUE TITLE
TypeError: GaussianRasterizationSettings

### ISSUE THREAD

**Issue by ReFantasy** [XJay18/NeuMA#2]
Dear Authors,

We greatly appreciate your work, and we encountered an error while running your code strictly following the given instructions. We hope to receive your assistance in resolving this issue. The error message is as follows:
```
===================================
Optimizing initial velocity ...

[velocity] Simulation steps: 20
[velocity] Using substeps: 1
[velocity] Using views: ['d_2']
  [pcd] | num_points: 25744
  x: [0.2522614747285843, 0.7574655413627625]
  y: [0.023701246827840805, 0.5439990758895874]
  z: [0.2527327984571457, 0.7463521659374237]
[velocity] Using dt: 0.001
[velocity] Using eps: 6e-07
[velocity] Using clip bound: 0.1
[velocity] Using mask data: False
[velocity] Using pixel loss: l2
  0%|                                                                                                                                                              | 0/200 [00:00<?, ?it/s]
Traceback (most recent call last):                                                                                                                                 | 0/200 [00:00<?, ?it/s]
  File "/home/refantasy/code/NeuMA/experiments/finetune.py", line 670, in <module>
    finetune(cfg)
  File "/home/refantasy/code/NeuMA/experiments/finetune.py", line 635, in finetune
    optimize_init_velocity(
  File "/home/refantasy/code/NeuMA/experiments/finetune.py", line 163, in optimize_init_velocity
    render = diff_rasterization(
  File "/home/refantasy/code/NeuMA/modules/tune/utils.py", line 345, in diff_rasterization
    rasterizer = get_rasterizer(
  File "/home/refantasy/code/NeuMA/modules/d3gs/gaussian_renderer/__init__.py", line 103, in get_rasterizer
    raster_settings = GaussianRasterizationSettings(
TypeError: GaussianRasterizationSettings.__new__() missing 1 required positional argument: 'antialiasing'
```
Thank you for your attention to this matter. We look forward to your guidance and support in resolving this issue.

**Comment by XJay18** [comment]
Hi! Thank you for your interest in our work! As pointed out [here](https://github.com/XJay18/NeuMA/issues/1#issuecomment-2465945771) (No. 2&3), the issue seems related to recent updates of [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting). For now, you may follow the suggested modifications in that comment. There may be some updates to the code later.

**Comment by ReFantasy** [comment]
> Hi! Thank you for your interest in our work! As pointed out [here](https://github.com/XJay18/NeuMA/issues/1#issuecomment-2465945771) (No. 2&3), the issue seems related to recent updates of [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting). For now, you may follow the suggested modifications in that comment. There may be some updates to the code later.

Thank you for your patient answer. I have already resolved this issue.

I have another minor question regarding the configuration file for synthetic data experiments. We didn't find any information about kernels_path and mesh_path in the README file on your GitHub page. However, we downloaded the pre-trained files you provided and filled in the paths for the assets section. We are unsure if this is the correct approach.

file: finetune-bb.yaml
```
kernels_path: /home/refantasy/code/NeuMA/experiments/assets/bouncyball/kernels.ply
mesh_path: /home/refantasy/code/NeuMA/experiments/assets/bouncyball/mesh.ply
```

Thank you for your assistance in resolving this query. We look forward to your response.

**Comment by XJay18** [comment]
Hi!

`kernels_path` and `mesh_path` are only required if `experiments/assets` does not contain the folder with the name `$sim_data_name`. Since you have downloaded our assets and put them in the right place, you do not need to modify those values. The script will use the stored assets to avoid processing them each time.

If you want to create new assets (with new `$sim_data_name`), then you need to specify these values. In our experiments, we use [gaussian-splatting](https://github.com/graphdeco-inria/gaussian-splatting) to get the reconstructed Gaussian kernels, and set `kernels_path` to the output file. We use [gaussian-opacity-fields](https://github.com/autonomousvision/gaussian-opacity-fields) to get the surface mesh, and set `mesh_path` to the output file.

You may also refer to our code for asset preparation [here](https://github.com/XJay18/NeuMA/blob/058d04d4d1a0ba9a5d44ac02981d063c327c5dcd/modules/tune/utils.py#L173) for more details.

**Comment by ReFantasy** [comment]
Thank you for your patient and detailed response. It has resolved my confusion. I will close this issue.
