### ISSUE TITLE
How to Preprocess NeuMA Synthetic Data to Obtain Initial Point Cloud Files

### ISSUE THREAD

**Issue by jiang-han98** [XJay18/NeuMA#6]
Hello, your experiment was very exciting, but I encountered a problem while trying to use NeuMA synthesize data. As you mentioned in your paper "We then adopt the standard training pipeline of 3DGS (optionally with the anisotropy regularizer
used in [17, 85] to encourage Gaussian kernels to be more evenly shaped to reduce spiky artifacts) to
get a dedicated object reconstruction represented by a set of Gaussian kernels {K(i)}.", when I used Colmap to reconstruct NeuMA synthesized data, I was unable to extract enough feature points for reconstruction, resulting in the inability to generate the initial point cloud file for 3D Gaussian Splatting input. How did you process the synthesized data? I am looking forward to and thank you very much for your reply.

**Comment by XJay18** [comment]
Hi, it is expected that colmap will fail on the synthetic objects because they lack texture information. However, you do not need to run colmap for the synthetic data as we have provided camera poses (e.g., `data/BouncyBall/*.json`). The format of the camera information is similar to that of the NerfSynthetic. So, you should refer to [readNerfSyntheticInfo](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/scene/dataset_readers.py#L221-L255) and [readCamerasFromTransforms](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/scene/dataset_readers.py#L179-L219) as a starting point for loading the synthetic data.

BTW, we also provided reconstructed Gaussian kernels, which you can access [here](https://1drv.ms/f/c/3f1ccc11f481c100/EgQDL270OjxDmbXQhMB-IbcBwK89e2xQkpZCrWmlxsQC6A?e=GhJlH9) (see the `assets` folder) .

**Comment by jiang-han98** [comment]
Thank you so much for your answer！ It perfectly solved my problem.
